import React, { useState } from 'react';
import { Download, FileText, Mail, Check, Copy } from 'lucide-react';

export default function ExportModal({ data, onClose }) {
  const [copiedRfq, setCopiedRfq] = useState(false);

  if (!data || !data.recommended) return null;

  const { recommended, annual_impact } = data;
  const bom = recommended.bom || [];
  const dieline = recommended.dieline || {};

  const rfqTemplate = `SUBJECT: RFQ - Custom Eco Packaging (${recommended.name})

Dear Packaging Supplier,

We are requesting a quotation for manufacturing custom eco-friendly packaging specifications generated by EcoPack.

PROJECT DETAILS:
- Packaging Design: ${recommended.name}
- Outer Material: ${recommended.outer_material}
- Inner Cushioning: ${recommended.inner_material}
- Dimensions (Outer): ${dieline.outer_length_cm || 14} × ${dieline.outer_width_cm || 10} × ${dieline.outer_height_cm || 8} cm
- Target Unit Cost: <$${recommended.unit_cost_usd} / unit
- Annual Order Quantity: ${annual_impact.annual_volume.toLocaleString()} units
- Sustainability Requirement: ${recommended.recyclability_score}% regional recyclability / compostability compliant.

Please reply with your MOQ, lead time, tooling cost, and unit price break structure.

Best regards,
Resonance EcoPack Team`;

  const copyRfqToClipboard = () => {
    navigator.clipboard.writeText(rfqTemplate);
    setCopiedRfq(true);
    setTimeout(() => setCopiedRfq(false), 3000);
  };

  const downloadBomCsv = () => {
    let csvContent = "data:text/csv;charset=utf-8,Component,Quantity,Mass (g),Est. Cost ($)\n";
    bom.forEach(b => {
      csvContent += `"${b.item}","${b.qty}",${b.mass_g},${b.cost_usd}\n`;
    });
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `EcoPack_BOM_${recommended.id}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(5, 59, 44, 0.4)', backdropFilter: 'blur(8px)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px' }}>
      <div className="glass-panel" style={{ width: '100%', maxWidth: '750px', maxHeight: '90vh', overflowY: 'auto', padding: '28px', background: '#FFFFFF' }}>
        
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', borderBottom: '1px solid var(--border-soft)', paddingBottom: '14px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <FileText size={24} color="var(--brand-primary)" />
            <div>
              <h3 style={{ fontSize: '1.2rem', fontWeight: '800', color: 'var(--text-heading)' }}>Export Specification & RFQ Hub</h3>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Generate BOM sheets, carbon reports, and supplier RFQ emails</p>
            </div>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', fontSize: '1.2rem', cursor: 'pointer' }}>✕</button>
        </div>

        {/* Bill of Materials (BOM) Section */}
        <div style={{ marginBottom: '24px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
            <h4 style={{ fontSize: '0.95rem', fontWeight: '700', color: 'var(--text-heading)' }}>1. Bill of Materials (BOM) Table</h4>
            <button onClick={downloadBomCsv} className="btn-secondary" style={{ padding: '4px 10px', fontSize: '0.75rem' }}>
              <Download size={12} /> Download CSV
            </button>
          </div>

          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem', textAlign: 'left', background: 'var(--bg-secondary)', borderRadius: '8px', border: '1px solid var(--border-soft)' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--border-soft)', color: 'var(--text-muted)' }}>
                <th style={{ padding: '8px 12px' }}>Component Item</th>
                <th style={{ padding: '8px 12px' }}>Quantity</th>
                <th style={{ padding: '8px 12px' }}>Mass (g)</th>
                <th style={{ padding: '8px 12px' }}>Est. Cost ($)</th>
              </tr>
            </thead>
            <tbody>
              {bom.map((b, idx) => (
                <tr key={idx} style={{ borderBottom: '1px solid var(--border-soft)' }}>
                  <td style={{ padding: '8px 12px', fontWeight: '600' }}>{b.item}</td>
                  <td style={{ padding: '8px 12px' }}>{b.qty}</td>
                  <td style={{ padding: '8px 12px' }}>{b.mass_g} g</td>
                  <td style={{ padding: '8px 12px' }}>${b.cost_usd}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Supplier Request for Quote (RFQ) Sheet Generator */}
        <div style={{ marginBottom: '24px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
            <h4 style={{ fontSize: '0.95rem', fontWeight: '700', color: 'var(--text-heading)' }}>2. Supplier RFQ Email Template</h4>
            <button onClick={copyRfqToClipboard} className="btn-primary" style={{ padding: '4px 10px', fontSize: '0.75rem' }}>
              {copiedRfq ? <Check size={12} /> : <Copy size={12} />} {copiedRfq ? 'Copied!' : 'Copy RFQ'}
            </button>
          </div>

          <textarea 
            readOnly 
            value={rfqTemplate}
            rows={10}
            className="form-input"
            style={{ width: '100%', fontFamily: 'monospace', fontSize: '0.8rem', lineHeight: '1.4', background: 'var(--bg-secondary)', resize: 'none' }}
          />
        </div>

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
          <button onClick={() => window.print()} className="btn-primary">
            <FileText size={16} /> Print Full Specification Sheet PDF
          </button>
          <button onClick={onClose} className="btn-secondary">Close</button>
        </div>

      </div>
    </div>
  );
}
